name: daredux

packages:
  - packages/**

scripts:
  build_ext: dart run devtools_extensions build_and_copy --source=packages/redux_devtools_extension_ui --dest=packages/redux_devtools_extension/extension/devtools
